<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test metrics_register_SUITE:register result</title>
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" href="../../ct_default.css" type="text/css">
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<a name="top"></a><pre>
=== Test case: <a href="metrics_register_suite.src.html#register-1">metrics_register_SUITE:register/1</a> (click for source code)

=== Config value:

    [{watchdog,<0.16195.0>},
     {preset,"ldap_mnesia"},
     {tc_logfile,"/home/travis/build/esl/MongooseIM/test/ejabberd_tests/ct_report/ct_run.test@testing-gce-86d69b31-37da-4b19-835a-0a23b1d633d1.2016-03-25_13.36.27/ejabberd_tests.tests.metrics_register_SUITE.logs/run.2016-03-25_13.45.17/metrics_register_suite.register.html"},
     {tc_group_properties,[{name,registration},sequence]},
     {tc_group_path,[]},
     {data_dir,"/home/travis/build/esl/MongooseIM/test/ejabberd_tests/tests/metrics_register_SUITE_data/"},
     {priv_dir,"/home/travis/build/esl/MongooseIM/test/ejabberd_tests/ct_report/ct_run.test@testing-gce-86d69b31-37da-4b19-835a-0a23b1d633d1.2016-03-25_13.36.27/ejabberd_tests.tests.metrics_register_SUITE.logs/run.2016-03-25_13.45.17/log_private/"}]

=== Current directory is "/home/travis/build/esl/MongooseIM/test/ejabberd_tests/ct_report/ct_run.test@testing-gce-86d69b31-37da-4b19-835a-0a23b1d633d1.2016-03-25_13.36.27"

=== Started at 2016-03-25 13:45:17

<br />

<div class="ct_error_notify"><b>*** CT Error Notification 2016-03-25 13:45:17.488 ***</b>
metrics_helper:assert_counter failed on line 30
Reason: {badmatch,{value,4}}

<a href="#end">Full error description and stacktrace</a>
</div>
=== WARNING: end_per_testcase crashed!
Reason: {badmatch,
            {error,
                {connection_step_failed,
                    {{escalus_session,authenticate},
                     {client,undefined,escalus_tcp,#Port<0.23554>,false,
                         false,<0.16200.0>,undefined},
                     [{username,<<"alicE">>},
                      {server,<<"localhost">>},
                      {host,<<"localhost">>},
                      {port,5222},
                      {auth,{escalus_auth,auth_plain}},
                      {wspath,undefined},
                      {username,<<"alicE">>},
                      {server,<<"localhost">>},
                      {password,<<"matygrysa">>}],
                     [{compression,false},
                      {starttls,true},
                      {stream_management,true},
                      {advanced_message_processing,true},
                      {auth_plain,true},
                      {auth_sasl_oauth,true},
                      {auth_digest_md5,true},
                      {auth_sasl_scram_sha1,true}]},
                    {auth_failed,<<"alicE">>,
                        {xmlel,<<"failure">>,
                            [{<<"xmlns">>,
                              <<"urn:ietf:params:xml:ns:xmpp-sasl">>}],
                            [{xmlel,<<"not-authorized">>,[],[]}]}}}}}
Line: [{escalus_users,delete_user,274},
              {test_server,do_end_per_testcase,1299},
              {test_server,run_test_case_eval1,1054},
              {test_server,run_test_case_eval,968}]

<a name="end"></a>


=== Ended at 2016-03-25 13:45:17
=== location [{metrics_helper,assert_counter,30},
              {test_server,ts_tc,1429},
              {test_server,run_test_case_eval1,1026},
              {test_server,run_test_case_eval,968}]
=== reason = no match of right hand side value {value,4}
  in function  metrics_helper:assert_counter/2 (metrics_helper.erl, line 30)
  in call from test_server:ts_tc/3 (test_server.erl, line 1429)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1026)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 968)
=== 
*** register failed.
    Skipping all other cases in sequence.
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>
</p>
<div class="copyright">Copyright &copy; 2016 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!date>Fri Mar 25 2016 13:45:17<!/date><br />
</div>
</center>
</body>
</html>
